#!/bin/sh

# PROVIDE: freq

freq_enable="${freq_enable-NO}"

. /etc/rc.subr

name=freq
rcvar=`set_rcvar`

restart_cmd="freq_restart"
start_cmd="freq_start"
status_cmd="freq_status"
stop_cmd="freq_stop"

cd /usr/local/etc/

PIDFILE=/var/freq/freq.pid
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin
SUSER=freq
STDOUT=/var/log/freq/stdout.txt
PYTHON=/usr/local/bin/python
START=/usr/local/share/freq/start.py
CFG=/usr/local/etc/freq.conf

freq_start()
{
    if [ -e $PIDFILE ]; then
        echo "$name is already running? $PIDFILE exists."
        exit
    fi
    echo -n "Starting $name: "
    su $SUSER -c "$PYTHON $START $CFG >$STDOUT 2>&1 &"
    echo "done."
}

freq_stop()
{
    if !([ -e $PIDFILE ]); then
        echo "$name is not running? $PIDFILE not found."
    fi
    echo -n "Stopping $name: "
    killall -u $SUSER >/dev/null 2>&1
    if [ -e $PIDFILE ]; then sleep 1; fi
    killall -u $SUSER -kill >/dev/null 2>&1
    sleep 1
    echo "done."
    rm -rf $PIDFILE
}

freq_restart()
{
freq_stop
freq_start
}

load_rc_config $name
run_rc_command "$1"
