#!/bin/sh

# PROVIDE: freq

freq_enable="${freq_enable-NO}"

. /etc/rc.subr

name=freq
rcvar=`set_rcvar`

restart_cmd="freq_restart"
start_cmd="freq_start"
status_cmd="freq_status"
stop_cmd="freq_stop"

cd /usr/local/etc/

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin
SUSER=freq
PYTHON=/usr/local/bin/python
START=/usr/local/share/freq/start.py
CFG=/usr/local/etc/freq.conf

freq_status()
{
    killall -0 -u $SUSER >/dev/null 2>&1
    echo $?
}

freq_start()
{
    echo -n "Starting $name: "
    su $SUSER -c "$PYTHON $START $CFG >/dev/null 2>&1 &"
    echo "done."
}

freq_stop()
{
    echo -n "Stopping $name: "
    killall -u $SUSER >/dev/null 2>&1
    sleep 3
    killall -u $SUSER -kill >/dev/null 2>&1
    sleep 2
    echo "done."
}

freq_restart()
{
freq_stop
freq_start
}

load_rc_config $name
run_rc_command "$1"
