#!/bin/sh

if [ -n "$2" ]; then echo -n $2
else
 if [ -r ./VERSION ]; then /usr/bin/python2.5 ./VERSION
 else
  echo -n $1.
  q=`svnversion -n`
  r=$?
  if [ $r -eq 0 ]; then echo -n $q; else echo -n 'dev'; fi
 fi
fi