alias_cleared cleared
alias_deleted deleted
alias_empty alias list is empty
alias_not_found alias not found
alias_saved saved
cleaned cleaned
current_lang Current language is English (en)
disco_error can't query
from_me me
from_you you
get_msglimit %s
google? google?
google_history_notfound history not found for 'next'
google_no_results no results
google_result %s\n%s (%s)
google_results %s\n(%s results)
groupchats currently i'm spending time in %s\n(total count: %s)
help_categories Categories: %s\nto get command list, type 'help category', e.g. 'help basic'
help_category %s.\nTo get help, you need type '.help command', e.g. '.help test'
help_not_found not found (%s)
help_other_languages unfortunabelly help for '%s' not implemented yet in language '%s'; use %s, to see help in other languages
help_saved ok
help_show This command placed in categories: %s\n\n%s
idle_error can't query
idle_result %s`s idle is %s
info %s %s's uptime is %s\nload average: %s stanza/sec, stanza length %s
invalid_syntax Syntax:\n%s
invalid_syntax_default Invalid syntax
joined Joined '%s'
lang_changed Language successfully changed
lang_list Available languages: %s
lang_msg_saved saved
lang_not_found Language '%s' not found. Use .lang_list to see list of available languages.
lang_other_languages unfortunabelly help for '%s' not implemented yet in language '%s'; use %s instead
lang_self English (en)
leaved Leaved '%s'
log.header <html><head><title>freq log</title></head><body>\n
log.record <p><i><font color="#999999">[%d.%m.%y %H:%M:%S]</font></i> %%s</p>\n
moderate_error can't
moderate_not_found who?
moderate_ok ok
msglimit_saved saved
muc_only this command available only in conference
muc_whois %s/%s\n%s(%s)\njoined %s\naccess level: %s
nick_update ok
nick_updated ok
not_allowed Not allowed.
ping_error can`t ping
pong pong from %s %s
pyexec.ok Successful!
see_private see private
stats_error unknown
stats_result Stats for %s\nTotal: %s users\nOnline: %s users
status_update ok
status_updated ok
test.passed passed
time_error unknown
uptime_error can't query
uptime_result %s's uptime is %s
version_error failed
version_result_jid on %s %s %s %s
version_result_nick %s use %s %s %s
version_result_self %s %s %s
version_result_your you use %s %s %s
whom? who?
ok O'key
noisy_already_on "noisy" mode already turned on
noisy_already_off "noisy" mode is not enabled
noisy_leave %s: you leave? :( (%s)
noisy_kick bustards! the killed %s?? %s?
noisy_ban %s banned... %s
noisy_rename %s: change nick??
noisy_join %s: hello
join_failed can't join to %s (with nick %s)\nerror:\n%s
join_success joined to %s with nick %s
join_slash invalid room or nick: "/" is not allowed
join_already_there I'm already in that room... if not, you should to ask my admin to give me command ".rejoin"
globmsg_sent sent to %s rooms
status_whom who?
disco_empty disco list is empty
censor censor from %s\nnick %s(%s)\ncensor: %s\n%s 
