alias_deleted удалил
alias_empty нет ни одного алиаса
alias_not_found нет такого алиаса
alias_saved сохранил
cleaned зачистка выполнена
current_lang текущий язык русский (ru)
disco_error не получилось
from_me меня
from_you тебя
get_msglimit %s
google? чо искать?
google_history_notfound нет истории поиска для 'next'
google_no_results не нашел
google_result %s\n%s (%s)
google_results %s\n(всего %s результатов)
groupchats сейчас я сижу в %s\n(всего %s конференций)
help_categories Категории: %s\nчтобы получить список команд в категории напиши 'help категория', например 'help basic'
help_category Команды в этой категории: %s.\nДля справки по команде пишите '.help команда', например '.help test'
help_not_found не найдено (%s)
help_other_languages к сожалению справка по '%s' пока не написана на языке '%s'; вы можете использовать вместо этого %s
help_saved ok\n
help_show Категории: %s\n\n%s
idle_error не получилось
idle_result %s молчит %s
info я, %s %s, работаю без остановок %s\nНагрузка: %s станз в секунду, средняя длина станзы %s байт.
invalid_syntax синтаксис:\n%s
invalid_syntax_default неправильный синтаксис
join_try пытаюсь зайти в <%s>...
lang_changed язык изменен
lang_list доступные языки - %s
lang_msg_saved записано
lang_not_found язык '%s' недоступен, или его не существует; используйте .lang_list для просмотра списка доступных языков.
lang_self Русский (ru)
leaved вышел из '%s'
log.header <html><head><title>freq log</title></head><body>\n
log.record <p><i><font color="#999999">[%d.%m.%y %H:%M:%S]</font></i> %%s</p>\n
moderate_error не получилося
moderate_not_found кого?
moderate_ok ok
msglimit_saved сохранено
muc_only команда доступна только в конференции
muc_whois %s/%s\n%s(%s)\nзашел в конфу %s\nуровень доступа: %s
nick_update ok
nick_updated ok
not_allowed фиг
ping_error не получается
pong понг от %s %s
pyexec.ok выполнено
see_private глянь приват
stats_error хз
stats_result Статистика %s\nВсего: %s\nОнлайн: %s
status_update ok
status_updated ok
test.passed норма
time_error хз
uptime_error хз
uptime_result %s работает без остановок %s
version_error не получилось
version_result_jid на %s %s %s %s
version_result_nick %s использует %s %s %s
version_result_self я %s %s, запущен под %s
version_result_your у тебя %s %s %s
whom? каво?
alias_cleared очищено
ok O'key
noisy_already_on "шумный" режим уже включён
noisy_already_off "шумный" режим не включён
noisy_leave %s: ты ушёл? :( (%s)
noisy_kick зачем кикнули %s?? %s?
noisy_ban %s зобанен: %s
noisy_rename %s: шифруешся??
noisy_join /me категорически приветствует %s
join_failed не получилось зайти в %s (c ником %s)\nстанза с ошибкой:\n%s
join_success зашёл в конфу %s с ником %s
join_slash в имени конфы и нике не должно быть /
join_already_there я уже сижу в той комнате... если это не так, то попросите админа бота дать команду .rejoin
globmsg_sent сообщение отправлено в %s конференций
status_whom кого?
disco_empty список пуст
cerberus_invalid_mode нет такого режима. Прочитай справку по команде
censor_list_empty список пуст
censor_subscribed вы подписались на цензор из %s
censor_unsubscribed вы отписались от цензора из %s
censor_nojid не вижу вашего jid..
censor_not_subscribed вы не подписаны на цензор из этой комнаты
censor_already_subscribed вы уже подписаны
censor цензор из %s\nник: %s(%s)\nцензор: %s\n%s
ERROR Произошла ошибка при обработке вашего сообщения. По возможности, сообщите об этом админу бота. Если вы админ, то прочитайте %s, для более подробного описания ошибки
rewrite_cycle превышен предел глубины рекурсии (%s уровней) при обработке вашего сообщения. Похоже на зацикливание. Такие проблемы могут возникать при неправильно настроенных алиасах.
rewrite_too_many_commands ошибка: слишком много команд, их должно быть не более %s
vcard_error не получилось
alias_saved_with_access алиас сохранён (уровень доступа к алиасу: %s, алиас будет выполняться с уровнем доступа %s)
alias_no_access у вас недостаточно прав, чтобы поставить такой высокий уровень выполнения алиаса
alias_not_allowed у вас недостаточно прав для выполнения этого алиаса
chatlog_joined зашёл в конференцию
chatlog_leaved вышел из конференции
chatlog_leaved_reason вышел из конференции: %s
chatlog_subject Тема: %s
chatlog_change_subject %s установил(а) тему: %s
chatlog_kicked выгнали из конференции
chatlog_banned запретили входить в конференцию
chatlog_kicked_reason выгнали из конференции: %s
chatlog_banned_reason запретили входить в конференцию: %s
chatlog_changed_nick сменил ник
chatlogs_enabled логирование включено
chatlogs_disabled логирование отключено
